snippet RUN "RUN command"
RUN $1
$0
endsnippet

snippet MAINTAINER "MAINTAINER command"
MAINTAINER Theo Massard <massar_t@etna-alternance.net>
$0
endsnippet

snippet FROM "Description"
FROM $1
$0
endsnippet

snippet CMD "CMD command"
CMD ['$1']
$0
endsnippet
